name: Git Sync
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  git-sync:
    if: ${{ github.repository == 'GameDev-Elsi/deploy-TrytoEscape-24' }}
    runs-on: ubuntu-latest
    steps:
      - name: 🔗 Synchronize Repository
        uses: wei/git-sync@v3
        with:
          source_repo: "https://GameDev-Elsi:${{ secrets.GH_TOKEN }}@github.com:GameDev-Elsi/deploy-TrytoEscape-24.git"
          source_branch: "main"
          destination_repo: "https://schematics-itdev:${{ secrets.GH_TOKEN }}@github.com:schematics-itdev/deploy-TrytoEscape-24.git"
          destination_branch: "main"
